FROM node:21-alpine

RUN apk add --no-cache dumb-init

WORKDIR /usr/app

COPY ./entrypoint.sh ./

EXPOSE 3000

# Start dumb-init for PID 1
ENTRYPOINT [ "/usr/bin/dumb-init", "--" ]

# Start react in the foreground
CMD [ "/bin/sh", "./entrypoint.sh" ]