import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import RecoilRootWrapper from "./components/recoilWrapper";
import ToastPopup from "./components/toastPopup";
import ReactQueryProviders from "@/hooks/useReactQuery";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <RecoilRootWrapper>
          <ReactQueryProviders>{children}</ReactQueryProviders>
          <ToastPopup />
        </RecoilRootWrapper>

        <div id="modal-root"></div>
      </body>
    </html>
  );
}
